version : "3"
services :
  postgres:
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: zupcommerce

  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:8080
