DROP SCHEMA IF EXISTS ezup CASCADE;

CREATE SCHEMA ezup;

CREATE TABLE IF NOT EXISTS ezup.produtos(
   ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   SKU VARCHAR(100) UNIQUE   NOT NULL,
   DESCRICAO           TEXT    NOT NULL,
   PRECO      DECIMAL DEFAULT '0.00',
   PESO       DECIMAL,
   ALTURA       DECIMAL,
   LARGURA 	DECIMAL,
   PROFUNDIDADE DECIMAL,
   FABRICANTE VARCHAR(200)
);


CREATE TABLE IF NOT EXISTS ezup.pedidos(
   ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   NOME_CLIENTE VARCHAR(200) NOT NULL,
   TELEFONE VARCHAR(30),
   VALOR_PRODUTOS DECIMAL DEFAULT '0.00',
   VALOR_DESCONTO DECIMAL DEFAULT '0.00',
   VALOR_TOTAL DECIMAL DEFAULT '0.00'
);

CREATE TABLE IF NOT EXISTS ezup.pedidos_produtos(
   ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   CONSTRAINT FK_PEDIDOS FOREIGN KEY (ID) REFERENCES ezup.produtos(ID),
   CONSTRAINT FK_PRODUTOS FOREIGN KEY (ID) REFERENCES ezup.pedidos(ID)
);